# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"
name: spark-local
services:
  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile
      args:
        SPARK_MODE: master
        SPARK_RPC_AUTHENTICATION_ENABLED: no
        SPARK_RPC_ENCRYPTION_ENABLED: no
        SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
        SPARK_SSL_ENABLED: no
        SPARK_USER: spark
    volumes:
    - ..:/workspaces:cached
    ports:
      - 9090:8080
  spark-worker:
    image: docker.io/bitnami/spark:3.1.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1      
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/plugins:/opt/airflow/plugins
    - ../airflow/conf:/opt/airflow/conf
    - ../airflow/.env:/opt/airflow/.env
    - ../airflow/standalone_admin_password.txt:/opt/airflow/standalone_admin_password.txt
    ports:
    - 8080:8080
  namenode:
    image: docker.io/gradiant/hdfs
    environment:
    - HDFS_CONF_dfs_replication=1
    volumes:
    - name:/hadoop/dfs
    command:
    - namenode
    ports:
    - 8020:8020
    - 50070:50070
    - 9870:9870
  datanode-0:
    image: docker.io/gradiant/hdfs
    environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - HDFS_CONF_dfs_replication=1
    volumes:
    - data-0:/hadoop/dfs
    command:
    - datanode
  kafka:
    image: docker.io/bitnami/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
volumes:
  data-0:
  name:
  kafka_data:
    driver: local
